# Generated by Django 2.1.2 on 2018-11-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artificialsatellite',
            name='classOfOrbit',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artificialsatellite',
            name='origin',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artificialsatellite',
            name='period',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artificialsatellite',
            name='typeOfOrbit',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artificialsatellite',
            name='users',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
