# Generated by Django 2.1.2 on 2018-11-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalsatellite',
            name='discoveredIn',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='naturalsatellite',
            name='meanRadius',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
