# Generated by Django 2.1.2 on 2018-11-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0003_auto_20181110_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artificalsatellite',
            name='purpose',
        ),
    ]
