# Generated by Django 2.1.2 on 2018-11-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellites', '0004_remove_artificalsatellite_purpose'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='artificalSatellite',
            new_name='artificialSatellite',
        ),
    ]
