# Generated by Django 2.1.2 on 2018-11-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constellation',
            name='brightestStar',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='constellation',
            name='meaning',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='constellation',
            name='origin',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
