# Generated by Django 2.1.2 on 2018-11-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constellations', '0002_auto_20181105_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constellation',
            name='id',
        ),
        migrations.AlterField(
            model_name='constellation',
            name='constellationName',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
