# Generated by Django 2.1.2 on 2018-11-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='galaxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galaxyName', models.CharField(default=None, max_length=100)),
                ('image', models.CharField(default=None, max_length=500)),
                ('constellation', models.CharField(default=None, max_length=100)),
                ('origin', models.CharField(default=None, max_length=3000)),
                ('notes', models.CharField(default=None, max_length=3000)),
            ],
        ),
    ]
