# Generated by Django 2.1.2 on 2018-11-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='notes',
            field=models.CharField(default=None, max_length=3000, null=True),
        ),
    ]
