# Generated by Django 2.1.2 on 2018-11-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galaxy', '0002_auto_20181102_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='galaxy',
            name='distance',
            field=models.DecimalField(decimal_places=5, default=None, max_digits=10, null=True),
        ),
    ]
