# Generated by Django 2.1.2 on 2018-11-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constellations', '0003_auto_20181106_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='star',
            fields=[
                ('starName', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('rightAscension', models.CharField(default=None, max_length=100, null=True)),
                ('declination', models.CharField(default=None, max_length=100, null=True)),
                ('apparentMagnitude', models.CharField(default=None, max_length=100, null=True)),
                ('distance', models.CharField(default=None, max_length=100, null=True)),
                ('spectralType', models.CharField(default=None, max_length=100, null=True)),
                ('mass', models.CharField(default=None, max_length=100, null=True)),
                ('temperature', models.CharField(default=None, max_length=100, null=True)),
                ('age', models.CharField(default=None, max_length=100, null=True)),
                ('confirmedPlanets', models.CharField(default=None, max_length=100, null=True)),
                ('notes', models.CharField(default=None, max_length=100, null=True)),
                ('constellationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constellations.constellation')),
            ],
        ),
    ]
