# Generated by Django 2.1.2 on 2018-11-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('constellations', '0003_auto_20181106_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='star',
            fields=[
                ('starName', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('constellationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constellations.constellation')),
            ],
        ),
    ]
